#!/usr/bin/bash
#allow the overwrite of the database and the command
if [ -z "$TENDPSQL" ]; then
    TENDPSQL="psql -d tend -P pager=off"
fi

if [ "$#" -eq "0" ]; then
    echo "--tend--"
    echo "    tend command [arguments, ...]"
    echo "commands:"
    echo "    ll - list long"
    echo "    ll"
    echo "    le - list all entities"
    echo "    le [id]"
    echo "    la - list all aliases for an entity"
    echo "    la [entity id]"
    echo "    ls - list all snippets for an entity"
    echo "    ls [entity id]"
    echo "    fa - find an entity by alias"
    echo "    fa [name]"
    echo "    fal - find an entity by alias long"
    echo "    fal [name]"
    echo "    fs - find a snippet by string"
    echo "    fs [string]"
    echo "    ae - add an entity"
    echo "    ae [name]"
    echo "    aa - add an alias to an entity"
    echo "    aa [id] [name]"
    echo "    as - add snippet to an entity"
    echo "    as [id]"
    echo "    ea - edit an entity"
    echo "    ea [id]"
    echo "    es - edit a snippet"
    echo "    es [id]"
    echo "    de - delete an entity"
    echo "    de [id]"
    echo "    da - delete an alias"
    echo "    da [id]"
    echo "    ds - delete a snippet"
    echo "    ds [id]"
else
    case $1 in
        "ll")
            echo "--list long--"
            $TENDPSQL -c "select id, (select string_agg(name, ', ' order by name) from alias where entity_id = entity.id) as aliases, created from entity order by 1;"
            ;;
        "le")
            echo "--list all entities--"
            if [ "$#" -eq "2" ]; then
                $TENDPSQL -c "select * from entity where id = ${2};"
            else
                $TENDPSQL -c "select * from entity;"
            fi
            ;;
        "la")
            echo "--list all aliases--"
            if [ "$#" -eq "2" ]; then
                entity_id="$2"
            else
                printf "enter entity id: "
                read -r entity_id
            fi
            $TENDPSQL -c "select name, id, updated from alias where entity_id = ${entity_id};"
            ;;
        "ls")
            echo "--list all snippets--"
            if [ "$#" -eq "2" ]; then
                entity_id="$2"
            else
                printf "enter entity id: "
                read -r entity_id
            fi
            $TENDPSQL -c "select data as snippet, id, updated from snippet where entity_id = ${entity_id};"
            ;;
        "fa")
            echo "--find entity--"
            if [ "$#" -eq "2" ]; then
                name="$2"
            else
                printf "enter name: "
                read -r name
            fi
            $TENDPSQL -c "select name, id, entity_id, updated from alias where name like '%${name}%' order by name;"
            ;;
        "fal")
            echo "--find entity--"
            if [ "$#" -eq "2" ]; then
                name="$2"
            else
                printf "enter name: "
                read -r name
            fi
            $TENDPSQL -c "select a.name, a.id, a.entity_id,
            (select string_agg(b.name, ', ' order by b.name) from alias b where a.entity_id = b.entity_id and a.id != b.id) as other_aliases,
            a.updated from alias a where a.name like '%${name}%' order by a.name;"
            ;;
        "fs")
            echo "--find snippet--"
            if [ "$#" -eq "2" ]; then
                string="$2"
            else
                printf "enter string: "
                read -r string
            fi
            $TENDPSQL -c "select data as snippet, id, entity_id, updated from snippet where data like '%${string}%';"
            ;;
        "ae")
            echo "--add entity and alias--"
            if [ "$#" -eq "2" ]; then
                name="$2"
            else
                printf "enter name: "
                read -r name
            fi
            $TENDPSQL -c "insert into entity default values; insert into alias (name) values ('${name}');select currval('entity_id_seq');"
            ;;
        "aa")
            echo "--add alias--"
            if [ "$#" -eq "3" ]; then
                id="$2"
                name="$3"
            elif [ "$#" -eq "2" ]; then
                id="$2"
                printf "enter name: "
                read -r name
            else
                printf "enter id: "
                read -r id
                printf "enter name: "
                read -r name
            fi
            $TENDPSQL -c "insert into alias (name, entity_id) values ('${name}', ${id}) returning id;"
            ;;
        "as")
            echo "--add snippet--"
            if [ "$#" -eq "2" ]; then
                id="$2"
            else
                printf "enter id: "
                read -r id
            fi
            #no this isnt security yes i know you can do sql injections here (youre running this locally you have a damn shell)
            #this this is because i dont want to have to sanitize it manually if i want to say shove json into the db
            data=$(sed -r "s/'/\\\\'/g" </dev/stdin)
            $TENDPSQL -c "insert into snippet (data,entity_id) values ('${data}', ${id}) returning id;"
            ;;
        "ea")
            echo "--edit alias--"
            if [ "$#" -eq "3" ]; then
                id="$2"
                string="$3"
                $TENDPSQL -c "update alias set name = '${string}' where id = ${id};"
            else
                if [ "$#" -eq "2" ]; then
                    id="$2"
                else
                    printf "enter id: "
                    read -r id
                fi
                $TENDPSQL -c "select name, id, entity_id, updated from alias where id = ${id};"
                printf "enter new alias: "
                read -r string
                $TENDPSQL -c "update alias set name = '${string}' where id = ${id};"
            fi
            ;;
        "es")
            echo "--edit snippet--"
            if [ "$#" -eq "2" ]; then
                id="$2"
            else
                printf "enter id: "
                read -r id
            fi
            $TENDPSQL -c "select data as snippet, id, entity_id, updated from snippet where id = ${id};"
            #see above rant
            data=$(sed -r "s/'/\\\\'/g" </dev/stdin)
            $TENDPSQL -c "update snippet set data = '${data}' where id = ${id};"
            ;;
        "de")
            echo "--delete entity--"
            if [ "$#" -eq "2" ]; then
                id="$2"
            else
                printf "enter id: "
                read -r id
            fi
            $TENDPSQL -c "delete from entity where id = ${id};"
            ;;
        "da")
            echo "--delete alias--"
            if [ "$#" -eq "2" ]; then
                id="$2"
            else
                printf "enter id: "
                read -r id
            fi
            $TENDPSQL -c "delete from alias where id = ${id};"
            ;;
        "ds")
            echo "--delete snippet--"
            if [ "$#" -eq "2" ]; then
                id="$2"
            else
                printf "enter id: "
                read -r id
            fi
            $TENDPSQL -c "delete from snippet where id = ${id};"
            ;;
        *)
            echo "unknown option $1"
            $0
            ;;
    esac
fi
